trigger:
- master

pool:
  vmImage: windows-latest

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.rr)

steps:
- task: NodeTool@0
  displayName: 'Use Node 12.19.0'
  inputs:
    versionSpec: 12.19.0

- task: npmAuthenticate@0
  displayName: 'npm authenticate'
  inputs:
    workingFile: .npmrc

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Create installer'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run pack'

- task: CopyFiles@2
  displayName: 'Copy installer to artifact staging directory'
  inputs:
    sourceFolder: 'dist'
    contents: |
        *.exe
    targetFolder: '$(Build.ArtifactStagingDirectory)\dist'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Substation_Installer'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)\dist'
    artifactName: 'Substation_Installer'