name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/device-painter/device-painter-pipeline
            azure-pipeline-name: 'ashish-srivastava-dev.js-e2e-express-server'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}